name: Verify Code
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  verify_code:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "JDK set-up"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn clean verify